site_name: Mon's Digital Garden

repo_url: https://github.com/NN66kk/Mon-Blog
repo_name: NN66kk/Mon-Blog
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: docs/templates
  language: zh
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.instant
    - navigation.path
    - toc.follow
    - search.highlight
    - search.suggest
    - search.share
    - content.code.copy
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: "\u5207\u6362\u5230\u6DF1\u8272\u6A21\u5F0F"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: blue grey
      toggle:
        icon: material/brightness-4
        name: "\u5207\u6362\u5230\u6D45\u8272\u6A21\u5F0F"

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - meta
  - footnotes
  - def_list
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  - roamlinks

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js

extra_css:
  - css/custom.css
